# Generated by Django 3.0.1 on 2019-12-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20191229_1435'),
    ]

    operations = [
    ]
