# Generated by Django 3.0.1 on 2019-12-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(max_length=250)),
                ('status', models.CharField(default=1, max_length=1)),
            ],
        ),
    ]
